# Generated by Django 6.0.3 on 2026-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
